config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :bagmons
  resources :battle
  get 'home/index'
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bagmon.rb
class Bagmon < ApplicationRecord
    belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :bagmons
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/bagmons_controller.rb
class BagmonsController < ApplicationController
  before_action :set_bagmon, only: %i[ show edit update destroy ]
  before_action :set_type_options, only: %i[ create new edit update ]

  def set_type_options
    @type_options = Type.all.pluck(:name, :id)
  end

  # GET /bagmons or /bagmons.json
  def index
    @bagmons = Bagmon.order(:number)
  end

  # GET /bagmons/1 or /bagmons/1.json
  def show
  end

  # GET /bagmons/new
  def new
    @bagmon = Bagmon.new
  end

  # GET /bagmons/1/edit
  def edit
  end

  # POST /bagmons or /bagmons.json
  def create
    @bagmon = Bagmon.new(bagmon_params)

    respond_to do |format|
      if @bagmon.save
        format.html { redirect_to bagmon_url(@bagmon), notice: "Bagmon was successfully created." }
        format.json { render :show, status: :created, location: @bagmon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bagmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bagmons/1 or /bagmons/1.json
  def update
    respond_to do |format|
      if @bagmon.update(bagmon_params)
        format.html { redirect_to bagmon_url(@bagmon), notice: "Bagmon was successfully updated." }
        format.json { render :show, status: :ok, location: @bagmon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bagmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bagmons/1 or /bagmons/1.json
  def destroy
    @bagmon.destroy

    respond_to do |format|
      format.html { redirect_to bagmons_url, notice: "Bagmon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bagmon
      @bagmon = Bagmon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bagmon_params
      params.require(:bagmon).permit(:number, :name, :image, :type_id)
    end
end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
    def index
      @bagmons = Bagmon.all
  
      if (params[:bagmon1] && params[:bagmon2]) 
        @bagmon1 = Bagmon.find(params[:bagmon1])
        @bagmon2 = Bagmon.find(params[:bagmon2])
  
        @rounds = []
        @winnerName = ''
        @winnerImg = ''
  
        lifeBagmon1 = 100
        lifeBagmon2 = 100
        bagmonInAttack = rand(1..2) == 1 ? @bagmon1 : @bagmon2

        while (lifeBagmon1 > 0 && lifeBagmon2 > 0) do 
  
          if (bagmonInAttack == @bagmon1)
            attackValue = rand(5..10)
            lifeBagmon2 -= attackValue
            @rounds << @bagmon1.name + " atacou " + @bagmon2.name + " e tirou " + attackValue.to_s + " pontos de vida. " + @bagmon2.name + " agora tem " + lifeBagmon2.to_s + " pontos de vida."
            bagmonInAttack = @bagmon2
          else
            attackValue = rand(5..10)
            lifeBagmon1 -= attackValue
            @rounds << @bagmon2.name + " atacou " + @bagmon1.name + " e tirou " + attackValue.to_s + " pontos de vida. " + @bagmon1.name + " agora tem " + lifeBagmon1.to_s + " pontos de vida."
            bagmonInAttack = @bagmon1
          end
        end

        if (lifeBagmon1 > 0)
          @winnerName << @bagmon1.name
          @winnerImg << @bagmon1.image
        else
          @winnerName << @bagmon2.name
          @winnerImg << @bagmon2.image
        end
      end
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bagmons_helper.rb
module BagmonsHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/bagmons/_form.html.erb
<head>
  <style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, Helvetica, sans-serif;
}

.container-form {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
}

.img-box img {
    height: 100px;
    margin-bottom: 10px;
}

.img-box {
    display: flex;
  justify-content: center;
  align-items: center;
  margin: 20px;
}

.content-box {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
}

.content-box .form-box {
    align-items: center;
    /* background-color: blue; */
    justify-content: center;
    width: 30%;
}

.content-box .form-box .ul {
    display: flex;
    align-items: center;
    justify-content: center;
}

.content-box .form-box .ul li {
    list-style: none;
    width: 60px;
    height: 60px;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 50%;
    margin: 0 7px;
    cursor: pointer;
    transition: 0.3s;
}

.content-box .form-box .ul li:hover {
    background: #e4e4e4;
}

.form-box .ul li img {
    width: 40px;
}

.content-box .form-box h2 {
    color: #0A265D;
    font-weight: 600;
    font-size: 2em;
    margin-bottom: 20px;
    text-transform: none;
    text-align: center;
}

.content-box .form-box .input-box {
    margin-bottom: 20px;
}

.content-box .form-box .input-box input {
    width: 100%;
    padding: 10px;
    outline: none;
    font-weight: 400;
    border: none;
    font-size: 17px;
    color: #0A265D;
    background-color: #ecf2f7;
    border-radius: 5px;
}

.content-box .form-box .input-box span {
    font-size: 16px;
    margin-bottom: 5px;
    display: inline-block;
    color: #0A265D;
    font-weight: 400;
}

.content-box .form-box .input-box input::placeholder {
    color: #a9adb6;
}


.content-box .form-box .input-box input[type=submit] {
    background: #0A265D;
    color: #fff;
    outline: none;
    border: none;
    font-weight: 500;
    cursor: pointer;
    font-size: 17px;
    transition: 0.3s;
}

.content-box .form-box .input-box input[type=submit]:hover {
    background: #3286ca;
}

.content-box .form-box .input-box p {
    color: #0A265D;
}
.content-box .form-box .input-box p a{
    color: #4aa4ee;
}

.content-box .form-box .input-box p a:hover{
    color: #3286ca;
}
.content-box .form-box h3
{
    color: #607d8b;
    text-decoration: none;
    margin: 40px 0 15px;
    font-weight: 500;
    text-align: center;
    font-size: 22px;
}
@media (max-width:868px) {
    .container-form .img-box{
        display: none;
    }
    .container-form .content-box{
        width: 100%;
    }
    .container-form .content-box .form-box{
        width: 100%;
        padding: 40px;
        background: white;
        margin: 50px;
    } 
    .container-form .content-box .form-box h3{
        margin: 30px 0 10px;
    } 
}

    .input-box .btn {
        text-align: center;
    }

  .input-box .btn button {
    padding: 5px;
    background-color: #FFD700;
    color: #0A265D;
    font-size: 15px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  </style>
</head>

<%= form_with(model: bagmon, local: true) do |form| %>
<body>
    <div class="container-form">
        <div class="content-box">
            <div class="form-box">
            <div class="img-box">
           
            </div>
                <h2>Criar Bagmon</h2>
                <form>
                    <div class="input-box">
                        <span>Numero</span>
                        <%= form.number_field :number, class: "form-control", placeholder: "Informe a numero/id do Bagmon" %>
                    </div>

                    <div class="input-box">
                        <span>Nome</span>
                       <%= form.text_field :name, class: "form-control", placeholder: "Informe o nome do Bagmon" %>
                    </div>

                    <div class="input-box">
                        <span>Imagem (URL)</span>
                        <%= form.text_field :image, class: "form-control", placeholder: "Informe a imagem do Bagmon" %>
                    </div>

                    <div class="input-box">
                        <span>Tipo do Bagmon</span>
                         <%= form.select("type_id", @type_options, {include_blank: 'Selecione...'}, {:multiple => false, class: "form-control"}) %>
                    </div>

                     <div class="input-box">
                        <%= form.submit "Enviar" %>
                    </div>

                     <div class="input-box">
                        <div class="btn">
                            <button> <%= link_to 'Voltar', bagmons_path %> </button>
                        </div>
                    </div>

                    <div class="input-box">
                      <% if bagmon.errors.any? %>
                        <div id="error_explanation">
                       <ul>
                          <span style="color: red">Ops! Problema ao salvar:</span>
                            <% bagmon.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                       <% end %>
                     </ul>
                    </div>
                    <% end %>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>
<% end %>

app/views/bagmons/_formEdit.html.erb
<head>
  <style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, Helvetica, sans-serif;
}

.container-form {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
}

.img-box img {
    border-radius: 20px;
    width: 100px;
    height: 100px;
    margin-bottom: 10px;
}

.img-box {
    display: flex;
  justify-content: center;
  align-items: center;
  margin: 20px;
}

.content-box {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
}

.content-box .form-box {
    align-items: center;
    /* background-color: blue; */
    justify-content: center;
    width: 30%;
}

.content-box .form-box .ul {
    display: flex;
    align-items: center;
    justify-content: center;
}

.content-box .form-box .ul li {
    list-style: none;
    width: 60px;
    height: 60px;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 50%;
    margin: 0 7px;
    cursor: pointer;
    transition: 0.3s;
}

.content-box .form-box .ul li:hover {
    background: #e4e4e4;
}

.form-box .ul li img {
    width: 40px;
}

.content-box .form-box h2 {
    color: #0A265D;
    font-weight: 600;
    font-size: 2em;
    margin-bottom: 20px;
    text-transform: none;
    text-align: center;
}

.content-box .form-box .input-box {
    margin-bottom: 20px;
}

.content-box .form-box .input-box input {
    width: 100%;
    padding: 10px;
    outline: none;
    font-weight: 400;
    border: none;
    font-size: 17px;
    color: #32324f;
    background-color: #ecf2f7;
    border-radius: 5px;
}

.content-box .form-box .input-box span {
    font-size: 16px;
    margin-bottom: 5px;
    display: inline-block;
    color: #32324f;
    font-weight: 400;
}

.content-box .form-box .input-box input::placeholder {
    color: #a9adb6;
}


.content-box .form-box .input-box input[type=submit] {
    background: #0A265D;
    color: #fff;
    outline: none;
    border: none;
    font-weight: 500;
    cursor: pointer;
    font-size: 17px;
    transition: 0.3s;
}

.content-box .form-box .input-box input[type=submit]:hover {
    background: #0A265D;
}

.content-box .form-box .input-box p {
    color: #32324f;
}
.content-box .form-box .input-box p a{
    color: #0A265D;
}

.content-box .form-box .input-box p a:hover{
    color: #0A265D;
}
.content-box .form-box h3
{
    color: #607d8b;
    text-decoration: none;
    margin: 40px 0 15px;
    font-weight: 500;
    text-align: center;
    font-size: 22px;
}
@media (max-width:868px) {
    .container-form .img-box{
        display: none;
    }
    .container-form .content-box{
        width: 100%;
    }
    .container-form .content-box .form-box{
        width: 100%;
        padding: 40px;
        background: white;
        margin: 50px;
    } 
    .container-form .content-box .form-box h3{
        margin: 30px 0 10px;
    } 
}

.input-box .btn button {
    padding: 5px;
    background-color: #369e35;
    color: #000;
    font-size: 15px;
    border: none;
    margin-right: 20px;
    width: 100px;
    border-radius: 5px;
  }

.input-box .btn .btn-delete {
    padding: 5px;
    background-color: #800000;
    color: #000;
    font-size: 15px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

.input-box .btn {
    width: 100%;
    text-align: center;
}

  </style>
</head>

<%= form_with(model: bagmon, local: true) do |formEdit| %>
<body>
    <div class="container-form">
        <div class="content-box">
            <div class="form-box">
            <div class="img-box">
                <img src="<%= @bagmon.image %>">
            </div>
                <h2>Editar Bagmon</h2>
                <form>
                    <div class="input-box">
                        <span>Numero</span>
                        <%= formEdit.number_field :number, class: "form-control", placeholder: "Informe a numero/id do Bagmon" %>
                    </div>

                    <div class="input-box">
                        <span>Nome</span>
                       <%= formEdit.text_field :name, class: "form-control", placeholder: "Informe o nome do Bagmon" %>
                    </div>

                    <div class="input-box">
                        <span>Imagem (URL)</span>
                        <%= formEdit.text_field :image, class: "form-control", placeholder: "Informe a imagem do Bagmon" %>
                    </div>

                    <div class="input-box">
                        <span>Tipo do Bagmon</span>
                         <%= formEdit.select("type_id", @type_options, {include_blank: 'Selecione...'}, {:multiple => false, class: "form-control"}) %>
                    </div>

                     <div class="input-box">
                        <%= formEdit.submit "Enviar" %>
                    </div>

                     <div class="input-box">
                        <div class="btn">
                            <button> <%= link_to 'Cancelar', bagmons_path %> </button>
                            <button class='btn-delete'> <%= link_to 'Excluir', bagmon, method: :delete, data: { confirm: 'Confirma a exclusão do Bagmon?' } %> </button>
                        </div>
                    </div>

                    <div class="input-box">
                      <% if bagmon.errors.any? %>
                        <div id="error_explanation">
                       <ul>
                          <span style="color: red">Ops! Problema ao salvar:</span>
                            <% bagmon.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                       <% end %>
                     </ul>
                    </div>
                    <% end %>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>
<% end %>

app/views/bagmons/edit.html.erb
<%= render 'formEdit', bagmon: @bagmon %>

app/views/bagmons/index.html.erb
<head>
  <style>
  * {
  margin: 0;
  padding: 0;
  }

  body {
    align-items: center;
    justify-content: center;
  }

  .main {
    display: flex; 
    flex-wrap: wrap;
    width: 100%;
    margin: 10px;
    gap: 1rem;
    justify-content: space-around; 
  }

  .main a {
    font-family: system-ui, -apple-system, Helvetica, Arial, sans-serif;
    text-decoration: none;
  }

  .card {
    color: white;
    display: flex; 
    flex-direction: column; 
    justify-content: center; 
    align-items: center; 
    height: 100%;
  }

  .card p {
    margin-bottom: 5px;
  }

  .bagmon {
    width: 100%; height: 100%; 
    display: flex; 
    justify-content: center; 
    align-items: center;
  }

  .title {
  display: flex;
  justify-content: center;
  align-items: center;
  font-family: system-ui, -apple-system, Helvetica, Arial, sans-serif;
  margin-top: 5vh;
  margin-bottom: 10vh;
  }

  .title h1 {
    color: #0A265D;
    font-family: system-ui, -apple-system, Helvetica, Arial, sans-serif;
  }

  .title p {
    color: #999;
    font-family: system-ui, -apple-system, Helvetica, Arial, sans-serif;
  }

  .titleText {
    text-align: center;
  }

  .buttonArea {
    position: absolute;
    right: 8vh;
    background: #0A265D;
    color: #fff;
    padding: 15px;
    font-weight: 500;
    align-items: center;
    justify-content: center;
    border-radius: 10px;
    cursor: pointer;
    font-size: 17px;
    transition: 0.3s;
  }

  .img-box img {
    height: 100px;
    margin-bottom: 10px;
}

.img-box {
    display: flex;
  justify-content: center;
  align-items: center;
  margin: 20px;
}

  </style>
<head>

<body> 
  <div class="form-box">
            <div class="img-box">
            <img class="imagem3" src="https://bagdex.com.br/wp-content/uploads/2022/09/logo_bagdex_01.png" /> 

<style>
.imagem3{
    transition: all 0.5s;
    cursor: pointer;
}

.imagem3:hover{
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
}
</style>
 <div class='buttonArea'>
    <%= link_to 'Criar novo Bagmon', new_bagmon_path %>
  </div>
  </div>

  <div class="main">
    <% @bagmons.each do |bagmon| %>
      <a style='background: <%=bagmon.type.color %>' href='/bagmons/<%= bagmon.id %>'>
        <div class="card">
          <div class="bagmon">
            <%= image_tag bagmon.image, size: "250x250" %>
          </div>
          <h2><%= bagmon.name %></h2>
          <p><%= bagmon.type.name %></p>
        </div>
      </a>
    <% end %>
  </div>
  
</body>

app/views/bagmons/new.html.erb
<%= render 'form', bagmon: @bagmon %>

app/views/bagmons/show.html.erb
<head>
  <style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, Helvetica, sans-serif;
  }

  .img-tst {
    margin-top: 30px;
    margin-bottom: 30px;
    border-radius: 10px;
    width: 350px;
    height: 350px;
    object-fit: contain;
  }

  .mainImage {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .btn {
    margin-top: 20px;
    text-align: center;
  }

  .btn button {
    padding: 5px;
    background-color: #0A265D;
    color: #000;
    font-size: 15px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  .btn .back-btn {
    padding: 5px;
    background-color: #FFD700;
    color: #000;
    font-size: 15px;
    margin-right: 20px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  .mainImage p {
    color: #0A265D;
  }

  </style>
</head>

<body>
  <div class="mainImage">
    <p>
      <img class='img-tst' src=<%= @bagmon.image %> >
    </p>
    <h2 style="color: <%= @bagmon.type.color %>">
      <%= @bagmon.name %>
    </h2>
    
    <p style="margin-top: 5px;">
      <strong>Numero:</strong>
      <%= @bagmon.number %>
    </p>
    
    <p style="margin-top: 5px;">
      <strong>Tipo:</strong>
      <%= @bagmon.type.name %>
    </p>


  <div class="btn">
    <button class="back-btn"> <%= link_to 'Voltar', bagmons_path %> </button>
    <button> <%= link_to 'Editar', edit_bagmon_path(@bagmon) %> </button>
  </div>

  </div>
</body>

app/views/types/_form.html.erb
<head>
  <style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, Helvetica, sans-serif;
}

.container-form {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
}

.img-box img {
    height: 200px;
    margin-bottom: 10px;
    border-radius: 15px;
}

.img-box {
display: flex;
  justify-content: center;
  align-items: center;
  margin: 20px;
}

.content-box {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
}

.content-box .form-box {
    align-items: center;
    /* background-color: blue; */
    justify-content: center;
    width: 30%;
}

.content-box .form-box .ul {
    display: flex;
    align-items: center;
    justify-content: center;
}

.content-box .form-box .ul li {
    list-style: none;
    width: 60px;
    height: 60px;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 50%;
    margin: 0 7px;
    cursor: pointer;
    transition: 0.3s;
}

.content-box .form-box .ul li:hover {
    background: #e4e4e4;
}

.form-box .ul li img {
    width: 40px;
}

.content-box .form-box h2 {
    color: #0A265D;
    font-weight: 600;
    font-size: 2em;
    margin-bottom: 20px;
    text-transform: none;
    text-align: center;
}

.content-box .form-box .input-box {
    margin-bottom: 20px;
}

.content-box .form-box .input-box input {
    width: 100%;
    padding: 10px;
    outline: none;
    font-weight: 400;
    border: none;
    font-size: 17px;
    color: #0A265D;
    background-color: #ecf2f7;
    border-radius: 5px;
}

.content-box .form-box .input-box span {
    font-size: 16px;
    margin-bottom: 5px;
    display: inline-block;
    color: #0A265D;
    font-weight: 400;
}

.content-box .form-box .input-box input::placeholder {
    color: #a9adb6;
}


.content-box .form-box .input-box input[type=submit] {
    background: #0A265D;
    color: #fff;
    outline: none;
    border: none;
    font-weight: 500;
    cursor: pointer;
    font-size: 17px;
    transition: 0.3s;
}

.content-box .form-box .input-box input[type=submit]:hover {
    background: #3286ca;
}

.content-box .form-box .input-box p {
    color: #0A265D;
}
.content-box .form-box .input-box p a{
    color: #4aa4ee;
}

.content-box .form-box .input-box p a:hover{
    color: #3286ca;
}
.content-box .form-box h3
{
    color: #607d8b;
    text-decoration: none;
    margin: 40px 0 15px;
    font-weight: 500;
    text-align: center;
    font-size: 22px;
}
@media (max-width:868px) {
    .container-form .img-box{
        display: none;
    }
    .container-form .content-box{
        width: 100%;
    }
    .container-form .content-box .form-box{
        width: 100%;
        padding: 40px;
        background: white;
        margin: 50px;
    } 
    .container-form .content-box .form-box h3{
        margin: 30px 0 10px;
    } 
}

    .input-box .btn {
        text-align: center;
    }

  .input-box .btn button {
    padding: 5px;
    background-color: #FFD700;
    color: #000;
    font-size: 15px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  </style>
</head>

<%= form_with(model: type, local: true) do |form| %>
<body>
    <div class="container-form">
        <div class="content-box">
            <div class="form-box">
            <div class="img-box">
            </div>
                <h2>Criar Tipo</h2>
                <form>
                    <div class="input-box">
                        <span>Nome</span>
                       <%= form.text_field :name, class: "form-control", placeholder: "Informe o nome do Tipo" %>
                    </div>

                    <div class="input-box">
                        <span>Cor (Hexadecimal)</span>
                        <%= form.text_field :image, class: "form-control", placeholder: "Informe a cor. Ex: #FFFFFF" %>
                    </div>

                     <div class="input-box">
                        <%= form.submit "Enviar" %>
                    </div>

                     <div class="input-box">
                        <div class="btn">
                            <button> <%= link_to 'Voltar', types_path %> </button>
                        </div>
                    </div>
                    <div class="input-box">
                      <% if type.errors.any? %>
                        <div id="error_explanation">
                       <ul>
                          <span style="color: red">Ops! Problema ao salvar:</span>
                            <% type.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                       <% end %>
                     </ul>
                    </div>
                    <% end %>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>
<% end %>

app/views/types/edit.html.erb
<%= render 'formEdit', type: @type %>

app/views/types/index.html.erb
<head>
  <style>
  * {
  margin: 0;
  padding: 0;
  font-family: Arial, Helvetica, sans-serif;
  }

  .main-info {
    align-items: center;
    margin: 10px;
  }

  .btn .btn-new {
    padding: 5px;
    background-color: #0A265D;
    font-size: 15px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  .btn {
    margin-top: 20px;
    align-items: center;
    justify-content: center;
  }

  table {
  border-collapse: collapse;
  width: 50%;
}

td, th {
  border: 1px solid #c9c9c9;
  text-align: left;
  color: #000;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
  </style>
</head>

<body>
  <div class="main-info">
    <h1 style="margin-bottom: 10px; color: #0A265D;">Tipos</h1>
      <table>
        <tr>
          <th>Tipo</th>
          <th>Opções</th>
        </tr>

      <% @types.each do |type| %> 
        <tr>
          <td><%= type.name %></td>
          <td><a style="color: #000" href=<%= edit_type_path(type) %>> Editar</a></td>
        </tr>
      <% end %>
      </table>
          <div class="btn">
            <button class='btn-new'><%= link_to 'Novo Tipo', new_type_path %> </button>
          </div>
        </div>
    </div>
  </div>
</body>

app/views/types/new.html.erb
<%= render 'form', type: @type %>

app/views/types/show.html.erb
<head>
  <style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, Helvetica, sans-serif;
}

.content {
  text-align: center;
  margin: 10px;
}

.content a {
  color: #000;
  font-size: 17px;
}

  .btn {
    margin-top: 20px;
  }

  .btn button {
    padding: 5px;
    color: #000;
    font-size: 15px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  .btn .back-btn {
    padding: 5px;
    color: #000;
    font-size: 15px;
    margin-right: 20px;
    border: none;
    width: 100px;
    border-radius: 5px;
  }

  h2 {
    margin-top: 8vh;
  }

  </style>
</head>

<body>
  <div class='content'>
  <h2><%= @type.name %></h2>
  <p style='color: <%= @type.color %>'> <%= @type.color %> </p>
  
    <div class="btn">
      <button class="back-btn"> <%= link_to 'Voltar', types_path %> </button>
      <button> <%= link_to 'Editar', edit_type_path(@type) %> </button>
    </div>
  </div>
</body>